### ISSUE TITLE
Trying to use with Metalsmith

### ISSUE THREAD

**Issue by custa1200** [frctl/twig#4]
Hi I am trying to build  a site in Metalsmith using Fractal, I have been previously using Handlebars for templating but was wanting to use Twig this time using the twig adapter but when I go to build Metalsmith I get the following:

```
Error parsing twig template /Users/custa/markjohnstonxd/fractal/design/templates/page/page.twig:
Error: ENOENT: no such file or directory, stat '@navigation'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.<anonymous> (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:8:20427)
    at Object.Twig.Templates.loadRemote (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:8:15035)
    at Twig.Template.importFile (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:8:17280)
    at Twig.logic.definitions.parse (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:9:15049)
    at Twig.logic.parse (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:9:21671)
    at parseToken (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:8:11471)
    at Array.forEach (native)
    at Object.Twig.forEach (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:8:822)
buffer.js:138
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:138:11)
    at new Buffer (buffer.js:65:10)
    at twig.load (/Users/custa/markjohnstonxd/node_modules/metalsmith-twig/lib/index.js:45:22)
    at loadTemplateFn (/Users/custa/markjohnstonxd/node_modules/twig/twig.min.js:8:20154)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

In my Twig template I have the following :
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ title }} - {{metadata.sitename}}</title>
    <meta name="description" content="{{ description }}">
  </head>
  <body>
    <div class="header">
        {% include '@navigation' %}
        {% block header %}

        {% endblock %}
    </div>
    <div class="body">
        {% block body %}

        {% endblock %}
    </div>
    <div class="footer">
        {% block footer %}

        {% endblock %}
        
    </div>
  </body>
</html>
```

**Comment by custa1200** [comment]
It does load the component if I use the full path but I feel that kind of defeating the purpose of Fractal and being able to use one set of templates with the Fractal styleguide as well as the site.

**Comment by Chapabu** [comment]
This feels like it's more of an issue with Metalsmith than Fractal. There are similar issues with Drupal that I've yet to look into too much (mainly because of my preference to use Fractal as a documentation tool rather than a live style guide).

I'm going to close this one for now, but if we can prove it's Fractal and not Metalsmith, then I'm happy for it to be reopened.
