### ISSUE TITLE
Can't render child components when using twig for both components and docs

### ISSUE THREAD

**Issue by levito** [frctl/twig#49]
When using twig for both components and docs (`fractal.components.engine(twigAdapter)` and `fractal.docs.engine(twigAdapter)`), I can't render child components anymore.

So I have `components/a/a.twig`, and `components/b/b.twig` with:
```
{% @render "a" %}
```

Visiting component B results in the following error:
```
Error: Error: Template @a not found
    at /path/to/node_modules/@frctl/twig/src/adapter.js:158:24
    at new Promise ()
    at TwigAdapter.render (/path/to/node_modules/@frctl/twig/src/adapter.js:140:16)
    at ComponentSource._renderVariant (/path/to/node_modules/@frctl/fractal/src/api/components/source.js:207:30)
    at _renderVariant.next ()
    at onFulfilled (/path/to/node_modules/co/index.js:65:19)
    at tryCatcher (/path/to/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/path/to/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/path/to/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/path/to/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/path/to/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/path/to/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/path/to/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/path/to/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/path/to/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/path/to/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/path/to/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/path/to/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/path/to/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/path/to/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/path/to/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/path/to/node_modules/bluebird/js/release/promise.js:649:10)
```

It works fine when not using twig as docs engine.

**Comment by risker** [comment]
This can be currently worked around by setting the docs adapter first, then the components adapter. This is also documented in the readme:
> However, due to the way this adapter currently extends Twig, it is necessary to set the docs engine before setting the components engine.

However, I'll keep this open since this behavior is certainly not normal and should be fixed at some point.
